tenant:
  name: ""
  backendImage: ""
  frontendImage: ""
  dbHost: ""
  dbSchema: ""
  dbUser: ""
  dbPassword: ""

ingress:
  enabled: true
  host: ""

backend:
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "2"
      memory: "2Gi"

frontend:
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "256Mi"
