apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.tenant.name }}-frontend
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.tenant.name }}-frontend
  template:
    metadata:
      labels:
        app: {{ .Values.tenant.name }}-frontend
    spec:
      containers:
        - name: frontend
          image: {{ .Values.tenant.frontendImage }}
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            requests:
              cpu: {{ .Values.frontend.resources.requests.cpu | quote }}
              memory: {{ .Values.frontend.resources.requests.memory | quote }}
            limits:
              cpu: {{ .Values.frontend.resources.limits.cpu | quote }}
              memory: {{ .Values.frontend.resources.limits.memory | quote }}
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 30
          env:
            - name: SPA_PATH
              value: /openmrs/spa
            - name: API_URL
              value: /openmrs
            - name: SPA_DEFAULT_LOCALE
              value: en
